version: "3"

services:
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"

  kafka:
    container_name: kafka
    image: wurstmeister/kafka:2.11-1.1.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      #KAFKA_CREATE_TOPICS: "topic-main:1:1"
    volumes:
      - kafka-persistence:/var/run/docker.sock
    depends_on:
      - zookeeper

  produtor_1:
    container_name: kafka_node_produtor_1
    restart: always
    build: ./produtor_1
    command: npm run dev
    ports:
      - 3333:3333
    volumes:
      - ./produtor_1:/app
    depends_on:
      - kafka

  produtor_2:
    container_name: kafka_node_produtor_2
    restart: always
    build: ./produtor_2
    command: npm run dev
    ports:
      - 3334:3334
    volumes:
      - ./produtor_2:/app
    depends_on:
      - kafka

  intermediator:
    container_name: kafka_node_intermediator
    restart: always
    build: ./intermediator
    command: npm run dev
    volumes:
      - ./intermediator:/app
    depends_on:
      - kafka
      
volumes:
  kafka-persistence: